name: Jira set comment env
on:
  workflow_call:
    inputs:
      URI:
        type: string
        required: true
      APPS:
        type: string
        required: true
    secrets:
      JIRA_API_KEY:
        required: true

jobs:
  update-jira:
    runs-on: [ self-hosted, docker-runner ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get project code
        id: get_project_code
        run: |
          echo "Repo name: ${{ github.event.repository.name }}"
          PROJECT_CODE=$(echo "${{ github.event.repository.name }}" | awk -F '-' '{print $1}')
          if [[ $PROJECT_CODE == "ta" ]]; then
            PROJECT='TRA'
          else
            PROJECT='TRR'
          fi

          echo "PROJECT=${PROJECT}" >> $GITHUB_ENV
          echo "Project Code: ${PROJECT}"

      - name: Get branch name and extract Jira issue ID
        id: extract_issue_id
        run: |
          echo "Branch name: ${GITHUB_REF_NAME}"
          ISSUE_ID=$(echo "${GITHUB_REF_NAME}" | grep -oE '[a-z]+-[0-9]+' | tr [:lower:] [:upper:])
          echo "Issue ID: ${ISSUE_ID}"
          echo "jira_issue_id=${ISSUE_ID}" >> $GITHUB_ENV

      - name: Adding ENV to comment
        if: ${{ env.jira_issue_id != '' }}
        id: adding_environment
        run: |
          echo "Updating Jira issue ${{ env.jira_issue_id }} with dev environment"

          COMMENT_JSON=$(cat <<EOF
          {
            "body": {
              "type": "doc",
              "version": 1,
              "content": [
                {
                  "type": "paragraph",
                  "content": [
                    {
                      "type": "text",
                      "text": "Выполнен успешный деплой"
                    }
                  ]
                },
                {
                  "type": "paragraph",
                  "content": [
                    {
                      "type": "text",
                      "text": "Компоненты: ${{inputs.APPS}}"
                    }
                  ]
                },
                {
                  "type": "paragraph",
                  "content": [
                    {
                      "type": "text",
                      "text": "Окружение: "
                    },
                    {
                      "type": "text",
                      "text": "${{inputs.URI}}",
                      "marks": [
                        {
                          "type": "link",
                          "attrs": {
                            "href": "${{inputs.URI}}",
                            "title": "Окружение"
                          }
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          }
          EOF
          )

          echo "${COMMENT_JSON}"

          curl --silent \
            --request POST \
            --url "https://trend-it.atlassian.net/rest/api/3/issue/${{ env.jira_issue_id }}/comment" \
            --header "Authorization: Basic ${{ secrets.JIRA_API_KEY }}" \
            --header "Content-Type: application/json" \
            --header 'Accept: application/json' \
            --data "$COMMENT_JSON"
