name: Notification

on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK:
        required: true

jobs:
  pachcaotification:
    if: ${{ github.event.inputs.location != 'ta-production' }}
    name: Pachca Notification
    runs-on: [ docker-runner ]
    steps:
      - uses: actions/checkout@v7
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v5

      - name: Notify Pachca
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          ENVIRONMENT: ${{ github.event.inputs.location || 'stage' }}
          BRANCH: ${{ env.GITHUB_REF_SLUG }}
          USER: ${{ github.actor }}
        run: |
          PAYLOAD=$(cat <<EOF
          {
            "message": "Пользователь: $USER\nОкружение: $ENVIRONMENT\nВетка: $BRANCH\n"
          }
          EOF
          )
          
          curl -X POST -H 'Content-Type: application/json' -d "$PAYLOAD" "$SLACK_WEBHOOK"


  pachcaNotificationPro:
    if: ${{ github.event.inputs.location == 'ta-production' }}
    name: Pachca Notification
    runs-on: [ docker-runner ]
    steps:
      - uses: actions/checkout@v7
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v5

      - name: Notify Pachca production
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          STATUS: ${{ job.status }}
          ENVIRONMENT: ${{ github.event.inputs.location }}
          APP_NAME: ${{ github.event.inputs.APP_NAME }}
          VERSION: ${{ github.event.inputs.APP_VERSION }}
          USER: ${{ github.actor }}
        run: |
          PAYLOAD=$(cat <<EOF
          {
            "message": "Пользователь: $USER\nОкружение: $ENVIRONMENT\nПриложение: $APP_NAME\nВерсия: $VERSION\nСтатус: $STATUS"
          }
          EOF
          )
          
          curl -X POST -H 'Content-Type: application/json' -d "$PAYLOAD" "$SLACK_WEBHOOK"
