name: Set version to JIRA
on:
  workflow_call:
    inputs:
      APP_VERSION:
        description: "Application version"
        required: true
        type: string
      APP_NAME:
        description: "Application name"
        required: true
        type: string
    secrets:
      JIRA_API_KEY:
        required: true

jobs:
  update-jira:
    runs-on: [ docker-runner ]

    steps:

      - name: Get project code
        id: get_project_code
        run: |
          echo "Repo name: ${{ github.event.repository.name }}"
          REPO_NAME="${{ github.event.repository.name }}"
          PROJECT_CODE=$(echo "$REPO_NAME" | awk -F '-' '{print $1}')
          
          if [[ "$REPO_NAME" == "chats-ui" ]]; then
            BRANCH="${{ github.ref }}"
            if [[ "$BRANCH" == */crm-* ]]; then
              PROJECT='CRM'
            else
              echo "Branch '$BRANCH' не входит в CRM проект"
              exit 0
            fi
          elif [[ $PROJECT_CODE == "ta" ]]; then
            PROJECT='TRA'
          elif [[ $PROJECT_CODE == "crm" ]]; then
            PROJECT='CRM'
          else
            PROJECT='TRR'
          fi

          echo "PROJECT=${PROJECT}" >> $GITHUB_ENV
          echo "Project Code: ${PROJECT}"

      - name: Get branch name and extract Jira issue ID
        id: extract_issue_id
        run: |
          echo "Branch name: ${GITHUB_REF_NAME}"
          ISSUE_ID=$(echo "${GITHUB_REF_NAME}" | grep -oE '[a-z]+-[0-9]+' | tr [:lower:] [:upper:])
          echo "Issue ID: ${ISSUE_ID}"
          echo "jira_issue_id=${ISSUE_ID}" >> $GITHUB_ENV

      - name: Set comment to JIRA with fix version
        id: set_jira_fix_versions
        run: |
          echo "Link Jira issue ${{ env.jira_issue_id }} with version ${{ env.APP_NAME }}/$${{ env.APP_VERSION }}"

          COMMENT_JSON=$(cat <<EOF
          {
            "body": {
              "type": "doc",
              "version": 1,
              "content": [
                {
                  "type": "paragraph",
                  "content": [
                    {
                      "type": "text",
                      "text": "Component fix version",
                      "marks": [
                        {
                          "type": "strong"
                        }
                      ]
                    }
                  ]
                },
                {
                  "type": "paragraph",
                  "content": [
                    {
                      "type": "text",
                      "text": "${{ env.APP_NAME }}/${{ env.APP_VERSION }}"
                    }
                  ]
                }
              ]
            }
          }
          EOF
          )

          echo "${COMMENT_JSON}"

          curl --silent \
            --request POST \
            --url "https://trend-it.atlassian.net/rest/api/3/issue/${{ env.jira_issue_id }}/comment" \
            --header "Authorization: Basic ${{ secrets.JIRA_API_KEY }}" \
            --header "Content-Type: application/json" \
            --header 'Accept: application/json' \
            --data "$COMMENT_JSON"

    env:
      APP_VERSION: ${{ inputs.APP_VERSION }}
      APP_NAME: ${{ inputs.APP_NAME }}
