name: Set component to JIRA
on:
  workflow_call:
    inputs:
      APP_NAME:
        description: "Application name"
        required: true
        type: string
    secrets:
      JIRA_API_KEY:
        required: true

jobs:
  component:
    runs-on: [ self-hosted, docker-runner ]

    steps:
      - name: Get branch name and extract Jira issue ID
        id: extract_issue_id
        run: |
          RAW_REF="${{ github.ref }}"
          BRANCH_NAME="${RAW_REF#refs/heads/}"
          ISSUE_ID=$(echo "$BRANCH_NAME" | grep -oE '[A-Z]+-[0-9]+')
          echo "Branch: $BRANCH_NAME"
          echo "Issue ID: ${ISSUE_ID}"
          echo "jira_issue_id=${ISSUE_ID}" >> $GITHUB_ENV

      - name: Create Jira component
        id: creat_jira_component
        run: |
          RAW_REF="${{ github.ref }}"
          BRANCH_NAME="${RAW_REF#refs/heads/}"
          PROJECT=$(echo "${BRANCH_NAME}" | grep -oE '[A-Z]+')
          
          echo "Create Jira component ${{ env.APP_NAME }}. Project ${PROJECT}"
          
          CREATE_COMPONENT=$(cat <<EOF
          {
            "description": "Component ${{ env.APP_NAME }} created automatically",
            "name": "${{ env.APP_NAME }}",
            "project": "$PROJECT",
            "assigneeType": "PROJECT_LEAD"
          }
          EOF
          )

          echo "${CREATE_COMPONENT}"
          
          curl --silent \
            --request POST \
            --url "https://trend-it.atlassian.net/rest/api/3/component" \
            --header "Authorization: Basic ${{ secrets.JIRA_API_KEY }}" \
            --header "Content-Type: application/json" \
            --data "$CREATE_COMPONENT"
          
          echo "\nComponent: ${{ env.APP_NAME }}"
          echo "jira_component=${{ env.APP_NAME }}" >> $GITHUB_ENV

      - name: Update Jira issue with Component
        id: update_jira
        run: |
          echo "Updating Jira issue ${{ env.jira_issue_id }} set component: ${{ env.APP_NAME }}"

          SET_COMPONENT_JSON=$(cat <<EOF
          {
            "update": {
              "components": [
                {
                  "add": {
                    "name": "${{ env.jira_component }}"
                  }
                }
              ]
            }
          }
          EOF
          )

          HTTP_CODE=$(curl --silent --output /dev/null --write-out "%{http_code}" \
          --request PUT \
          --url "https://trend-it.atlassian.net/rest/api/3/issue/${{ env.jira_issue_id }}" \
          --header "Authorization: Basic ${{ secrets.JIRA_API_KEY }}" \
          --header "Content-Type: application/json" \
          --data "$SET_COMPONENT_JSON")
          
          if [[ "$HTTP_CODE" -ge 200 && "$HTTP_CODE" -lt 300 ]]; then
            echo  "Jira issue updated successfully with HTTP code $HTTP_CODE"
          else
            echo "Failed to update Jira issue. HTTP code: $HTTP_CODE"
            exit 1
          fi

    env:
      APP_NAME: ${{ inputs.APP_NAME }}
